# Generated by Django 4.2 on 2024-01-01 04:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(max_length=124)),
                ('full_name', models.CharField(max_length=124)),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(50, message='Value must be greater than or equal to 50'), django.core.validators.MaxValueValidator(100000, message='Value must be less than or equal to 100')])),
                ('email', models.CharField(max_length=124)),
                ('city', models.CharField(max_length=124)),
                ('country', models.CharField(max_length=124)),
                ('mobile', models.CharField(max_length=124)),
                ('pancard', models.CharField(max_length=124)),
                ('comment', models.TextField()),
                ('payment_type', models.CharField(max_length=124)),
                ('is_anonymous', models.CharField(max_length=124)),
                ('status', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='UpiTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.donor')),
            ],
        ),
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=124)),
                ('bank_name', models.CharField(max_length=124)),
                ('transaction_date', models.DateField()),
                ('other_details', models.TextField()),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.donor')),
            ],
        ),
    ]
