# Generated by Django 4.2.7 on 2023-12-13 10:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('donation_type', models.CharField(choices=[('genral_donation', 'general_donation'), ('zakat', 'zakat'), ('interest_offloading', 'interest_offloading')], max_length=124)),
                ('full_name', models.CharField(max_length=124)),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(50, message='Value must be greater than or equal to 50'), django.core.validators.MaxValueValidator(100000, message='Value must be less than or equal to 100')])),
                ('email', models.CharField(max_length=124)),
                ('city', models.CharField(max_length=124)),
                ('country', models.CharField(max_length=124)),
                ('mobile', models.CharField(max_length=124)),
                ('pancard', models.CharField(blank=True, max_length=124, null=True)),
                ('comment', models.TextField()),
                ('payment_type', models.CharField(choices=[('bank_transfer', 'bank_transfer'), ('upi/credit_card/', 'upi')], max_length=124)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UpiTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('signature', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upi_transaction', to='donor.donor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=124)),
                ('bank_name', models.CharField(max_length=124)),
                ('transaction_date', models.DateField()),
                ('other_details', models.CharField(blank=True, max_length=124, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transaction', to='donor.donor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
