# Generated by Django 3.2 on 2023-12-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankTransfer',
            new_name='BankTransaction',
        ),
        migrations.AlterField(
            model_name='donor',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donor',
            name='pancard',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
    ]
