# Generated by Django 4.2.7 on 2023-12-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donation_type',
            field=models.CharField(choices=[('bank_transfer', 'bank_transfer'), ('upi/credit_card/', 'upi')], max_length=124),
        ),
    ]
