# Generated by Django 3.2 on 2023-12-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20231212_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='other_details',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
    ]
