# Generated by Django 4.2 on 2024-03-18 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('make_withdrawal', models.CharField(blank=True, max_length=124, null=True)),
                ('withdrawal_status', models.CharField(blank=True, max_length=124, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('donation_type', models.CharField(choices=[('General_Donation', 'General_Donation'), ('Zakat', 'Zakat'), ('Interest_Offloading', 'Interest_Offloading')], max_length=124)),
                ('full_name', models.CharField(blank=True, max_length=124, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.CharField(blank=True, max_length=124, null=True)),
                ('city', models.CharField(blank=True, max_length=124, null=True)),
                ('country', models.CharField(blank=True, max_length=124, null=True)),
                ('mobile', models.CharField(blank=True, max_length=124, null=True)),
                ('pancard', models.CharField(blank=True, max_length=124, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('payment_type', models.CharField(choices=[('Bank_Transfer', 'Bank_Transfer'), ('UPI', 'UPI')], max_length=124)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=124)),
                ('is_approved', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(blank=True, max_length=256, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=124, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('other_details', models.CharField(blank=True, max_length=124, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donors', to='campaigns.campaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
    ]
