# Generated by Django 4.2.7 on 2023-12-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banktransaction',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='upitransaction',
            options={'ordering': ('-created_at',)},
        ),
    ]
