# Generated by Django 4.2.7 on 2023-12-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_alter_banktransaction_options_alter_donor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banktransaction',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterModelOptions(
            name='upitransaction',
            options={'ordering': ('-created_on',)},
        ),
        migrations.RenameField(
            model_name='banktransaction',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='banktransaction',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='upitransaction',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='upitransaction',
            old_name='updated_at',
            new_name='updated_on',
        ),
    ]
