# Generated by Django 4.2.7 on 2024-01-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_donor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
