# Generated by Django 4.2 on 2024-01-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_banktransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
