# Generated by Django 4.2 on 2024-03-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_remove_withdrawal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='make_withdrawal',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='transfer_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='withdrawal_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=124),
        ),
    ]
