# Generated by Django 5.0.8 on 2024-08-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_alter_donor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
