# Generated by Django 4.2 on 2024-03-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_remove_donor_date_alter_donor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
