# Generated by Django 4.2 on 2024-03-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_remove_withdrawal_make_withdrawal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='withdrawal_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=124),
        ),
    ]
