# Generated by Django 4.2 on 2024-01-17 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_alter_donor_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(50, message='Value must be greater than or equal to 50'), django.core.validators.MaxValueValidator(100000, message='Value must be less than or equal to 100')]),
        ),
    ]
