# Generated by Django 4.2 on 2023-12-21 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_alter_campaign_catagory'),
        ('donors', '0003_alter_banktransaction_options_alter_donor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='campaign',
            field=models.ForeignKey(default='679e79ff-bcf0-4dea-bb36-4411698e6b2f', on_delete=django.db.models.deletion.CASCADE, related_name='donors', to='campaigns.campaign'),
            preserve_default=False,
        ),
    ]
