# Generated by Django 4.2 on 2024-03-27 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_alter_campaigncategory_image'),
        ('donors', '0004_alter_withdrawal_withdrawal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign'),
        ),
    ]
