# Generated by Django 4.2 on 2024-03-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_donor_bank_name_donor_other_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='make_withdrawal',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='withdrawal_status',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
    ]
