# Generated by Django 4.2 on 2024-03-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_alter_withdrawal_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='withdrawal_status',
            field=models.CharField(choices=[('No_Request', 'No_Request'), ('Paid', 'Paid'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=124),
        ),
    ]
