# Generated by Django 4.2 on 2024-03-16 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_withdrawal_make_withdrawal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upitransaction',
            name='donor',
        ),
        migrations.DeleteModel(
            name='BankTransaction',
        ),
        migrations.DeleteModel(
            name='UpiTransaction',
        ),
    ]
