# Generated by Django 4.2.7 on 2023-12-13 10:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('rasing_for', models.CharField(choices=[('self', 'self'), ('others', 'others')], max_length=124)),
                ('title', models.CharField(max_length=50)),
                ('goal_amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100, message='Value must be greater than or equal to 0'), django.core.validators.MaxValueValidator(1000, message='Value must be less than or equal to 100')])),
                ('fund_raised', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(100, message='Value must be greater than or equal to 0'), django.core.validators.MaxValueValidator(10000, message='Value must be less than or equal to 100')])),
                ('location', models.CharField(max_length=124)),
                ('zakat_eligible', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=124)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('completed', 'completed'), ('rejected', 'completed')], default='pending', max_length=124)),
                ('description', models.TextField()),
                ('summary', models.TextField()),
                ('is_successfull', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_reported', models.BooleanField(default=False)),
                ('is_scholarship', models.BooleanField(default=False)),
                ('course', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignCatagory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/media_files/')),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KycDetails',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('pan_card', models.CharField(max_length=10)),
                ('pan_card_image', models.ImageField(blank=True, null=True, upload_to='static/media_files/')),
                ('adhar_card', models.CharField(max_length=16)),
                ('adhar_card_image', models.ImageField(blank=True, null=True, upload_to='static/media_files/')),
                ('other_details', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_details', to='campaign.campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaigncatagory'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BenificiaryBankDetails',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('account_holder_name', models.CharField(max_length=124)),
                ('account_number', models.PositiveIntegerField()),
                ('bank_name', models.CharField(max_length=124)),
                ('branch_name', models.CharField(max_length=124)),
                ('ifsc_code', models.CharField(max_length=124)),
                ('passbook_image', models.ImageField(blank=True, null=True, upload_to='static/media_files/')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='campaign.campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
