# Generated by Django 3.2 on 2024-01-01 04:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignCatagories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='KycDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_card', models.CharField(max_length=10)),
                ('pan_img', models.ImageField(blank=True, null=True, upload_to='static/media_files/')),
                ('adhar_no', models.CharField(max_length=16)),
                ('adhar_image', models.ImageField(blank=True, null=True, upload_to='static/media_files/')),
                ('other_details', models.TextField()),
                ('isVerified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasing_for', models.CharField(choices=[('self', 'self'), ('others', 'others')], max_length=124)),
                ('title', models.CharField(max_length=50)),
                ('goal_amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100, message='Value must be greater than or equal to 0'), django.core.validators.MaxValueValidator(1000, message='Value must be less than or equal to 100')])),
                ('fund_raised', models.PositiveIntegerField(default=0, null=True)),
                ('location', models.CharField(max_length=124)),
                ('zakat_eligible', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=124)),
                ('description', models.TextField()),
                ('summary', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('is_features', models.BooleanField(default=False)),
                ('is_reported', models.BooleanField(default=False)),
                ('is_scholarship', models.BooleanField(default=False)),
                ('is_successful', models.BooleanField(default=False)),
                ('course', models.CharField(blank=True, max_length=50, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaigncatagories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BenificiaryBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=124)),
                ('account_number', models.PositiveIntegerField()),
                ('bank_name', models.CharField(max_length=124)),
                ('branch_name', models.CharField(max_length=124)),
                ('ifsc_code', models.CharField(max_length=124)),
                ('passbook_image', models.ImageField(blank=True, null=True, upload_to='static/media_files/')),
                ('Campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign')),
            ],
        ),
    ]
