# Generated by Django 3.2 on 2023-12-12 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benificiarybankdetails',
            old_name='Campaign',
            new_name='campaign',
        ),
        migrations.RenameField(
            model_name='kycdetails',
            old_name='isVerified',
            new_name='is_verified',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='fund_raised',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(100, message='Value must be greater than or equal to 0'), django.core.validators.MaxValueValidator(10000, message='Value must be less than or equal to 100')]),
        ),
    ]
