# Generated by Django 3.2 on 2023-12-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_campaign_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='fund_raised',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
