# Generated by Django 3.2 on 2023-12-12 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20231212_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdetails',
            name='campaign',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='benificiarybankdetails',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign'),
        ),
    ]
