# Generated by Django 3.2 on 2023-12-12 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_auto_20231212_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kycdetails',
            old_name='adhar_no',
            new_name='adhar_card',
        ),
        migrations.RenameField(
            model_name='kycdetails',
            old_name='adhar_image',
            new_name='adhar_card_image',
        ),
        migrations.RenameField(
            model_name='kycdetails',
            old_name='pan_img',
            new_name='pan_card_img',
        ),
    ]
