# Generated by Django 3.2 on 2023-12-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_auto_20231212_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdetails',
            name='other_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
