# Generated by Django 3.2 on 2023-12-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_alter_kycdetails_other_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_successfull',
            field=models.BooleanField(default=False),
        ),
    ]
