# Generated by Django 4.2 on 2024-05-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role_name',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Campaign_Approver', 'Campaign_Approver'), ('Campaign_Manager', 'Campaign_Manager'), ('Admin', 'Admin'), ('Accountant', 'Accountant'), ('Superadmin', 'Superadmin')], max_length=25, unique=True),
        ),
    ]
