# Generated by Django 4.2.7 on 2024-02-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("Individual", "Individual"), ("NGO", "NGO")],
                default="Individual",
                max_length=25,
            ),
        ),
    ]
