# Generated by Django 4.2.7 on 2023-12-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role_name',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Campaign_Approver', 'Campaign_Approver'), ('Campaign_Manager', 'Campaign_Manager'), ('Admin', 'Admin')], max_length=25, unique=True),
        ),
    ]
