# Generated by Django 4.2.7 on 2023-12-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userrole_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ('-created_on',)},
        ),
        migrations.RenameField(
            model_name='userrole',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='userrole',
            old_name='updated_at',
            new_name='updated_on',
        ),
    ]
