# Generated by Django 4.2.7 on 2023-12-19 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userrole_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='privacy_policy',
            new_name='accepted_policy',
        ),
    ]
