# Generated by Django 4.2 on 2024-01-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_images',
            field=models.ImageField(blank=True, null=True, upload_to='static/media_files/user_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
