# Generated by Django 4.2.7 on 2023-12-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalsetting',
            old_name='auto_approve',
            new_name='auto_approve_enabled',
        ),
        migrations.RenameField(
            model_name='generalsetting',
            old_name='email_verification',
            new_name='captcha_enabled',
        ),
        migrations.RenameField(
            model_name='generalsetting',
            old_name='facebook_login',
            new_name='email_verification_enabled',
        ),
        migrations.RenameField(
            model_name='generalsetting',
            old_name='google_login',
            new_name='facebook_login_enabled',
        ),
        migrations.RenameField(
            model_name='generalsetting',
            old_name='new_registration',
            new_name='new_registration_enabled',
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='google_login_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
