# Generated by Django 4.2.7 on 2024-02-26 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="CampaignEditApproval",),
    ]
