# Generated by Django 4.2 on 2024-03-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsetting',
            name='skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
