# Generated by Django 4.2.7 on 2023-12-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalsetting',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='landingpage',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='limit',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='pages',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='socialprofile',
            options={'ordering': ('-created_at',)},
        ),
    ]
