# Generated by Django 4.2.7 on 2024-01-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='avtar',
            field=models.ImageField(blank=True, null=True, upload_to='static/media_files/landing_page/'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='static/media_files/landing_page/'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='image_bottom',
            field=models.ImageField(blank=True, null=True, upload_to='static/media_files/landing_page/'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='image_category',
            field=models.ImageField(blank=True, null=True, upload_to='static/media_files/landing_page/'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='image_header',
            field=models.ImageField(blank=True, null=True, upload_to='static/media_files/landing_page/'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/media_files/landing_page/'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='logo_footer',
            field=models.ImageField(blank=True, null=True, upload_to='static/media_files/landing_page/'),
        ),
    ]
