# Generated by Django 4.2 on 2024-01-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='avtar',
            field=models.ImageField(blank=True, null=True, upload_to='static/media_files/'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='static/media_files/'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='image_bottom',
            field=models.ImageField(blank=True, null=True, upload_to='static/media_files/'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='image_category',
            field=models.ImageField(blank=True, null=True, upload_to='static/media_files/'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='image_header',
            field=models.ImageField(blank=True, null=True, upload_to='static/media_files/'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/media_files/'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='logo_footer',
            field=models.ImageField(blank=True, null=True, upload_to='static/media_files/'),
        ),
        migrations.AlterField(
            model_name='limit',
            name='max_file_size',
            field=models.CharField(max_length=5),
        ),
    ]
