# Generated by Django 4.2 on 2024-02-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsetting',
            name='date_format',
            field=models.CharField(choices=[('M d, Y', 'Feb 02, 2024'), ('d M, Y', '02 Feb, 2024'), ('Y-m-d', '2024-02-02'), ('m/d/Y', '02/02/2024')], default='M d, Y', max_length=12),
        ),
    ]
