# Generated by Django 4.2.7 on 2023-12-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_alter_generalsetting_options_alter_keyword_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalsetting',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterModelOptions(
            name='landingpage',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterModelOptions(
            name='limit',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterModelOptions(
            name='pages',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterModelOptions(
            name='socialprofile',
            options={'ordering': ('-created_on',)},
        ),
        migrations.RenameField(
            model_name='generalsetting',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='generalsetting',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='keyword',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='keyword',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='landingpage',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='landingpage',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='limit',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='limit',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='pages',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='pages',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='socialprofile',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='socialprofile',
            old_name='updated_at',
            new_name='updated_on',
        ),
    ]
