# Generated by Django 4.2 on 2024-03-28 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_generalsetting_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalsetting',
            old_name='skills',
            new_name='keywords',
        ),
    ]
