# Generated by Django 4.2 on 2024-02-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_generalsetting_date_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limit',
            name='max_file_size',
            field=models.CharField(choices=[('1 MB', '1 MB'), ('2 MB', '2 MB'), ('3 MB', '3 MB'), ('4 MB', '4 MB'), ('5 MB', '5 MB'), ('10 MB', '10 MB')], max_length=5),
        ),
        migrations.AlterField(
            model_name='limit',
            name='num_campaigns',
            field=models.PositiveIntegerField(choices=[(4, 4), (8, 8), (12, 12), (24, 24), (36, 36), (48, 48), (60, 60)]),
        ),
    ]
