# Generated by Django 4.2.7 on 2023-12-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_rename_auto_approve_generalsetting_auto_approve_enabled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='limit',
            old_name='file_size',
            new_name='max_file_size',
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='Keyword',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='input_field_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
