# Generated by Django 4.2.7 on 2024-02-20 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0002_alter_campaigneditapproval_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="generalsetting", name="welcome_subtitle",),
        migrations.RemoveField(model_name="limit", name="max_donation_amount",),
    ]
