# Generated by Django 4.2 on 2024-03-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_generalsetting_date_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsetting',
            name='welcome_subtitle',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
