# Generated by Django 4.2 on 2024-04-02 03:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankKYC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('account_holder_name', models.CharField(max_length=124)),
                ('account_number', models.CharField(max_length=240)),
                ('bank_name', models.CharField(max_length=124)),
                ('branch_name', models.CharField(max_length=124)),
                ('ifsc_code', models.CharField(max_length=124)),
                ('passbook_image', models.ImageField(blank=True, null=True, upload_to='campaign/kyc/')),
                ('pan_card', models.CharField(max_length=10)),
                ('pan_card_image', models.ImageField(blank=True, null=True, upload_to='campaign/kyc/')),
                ('adhar_card', models.CharField(max_length=16)),
                ('adhar_card_image', models.ImageField(blank=True, null=True, upload_to='campaign/kyc/')),
                ('other_details', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=124)),
                ('tandc_accept', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('campaign_image', models.ImageField(blank=True, null=True, upload_to='campaign/campaign_images/')),
                ('title', models.CharField(max_length=124)),
                ('goal_amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0, message='Value must be greater than or equal to 100'), django.core.validators.MaxValueValidator(1000000000, message='Value must be less than or equal to 1000000')])),
                ('fund_raised', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Value must be greater than or equal to 0'), django.core.validators.MaxValueValidator(100000, message='Value must be less than or equal to 100000')])),
                ('zakat_eligible', models.BooleanField(default=False)),
                ('rasing_for', models.CharField(choices=[('Self', 'Self'), ('Other', 'Other'), ('Family', 'Family'), ('Charity', 'Charity')], max_length=124)),
                ('location', models.CharField(max_length=124)),
                ('story', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=124)),
                ('end_date', models.DateField()),
                ('is_successful', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_reported', models.BooleanField(default=False)),
                ('is_withdrawal', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Campaigncategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(blank=True, max_length=130, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='campaign/category/')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CauseEdit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('campaign_data', models.JSONField(blank=True, default=dict, null=True)),
                ('campaign_image', models.ImageField(blank=True, null=True, upload_to='campaign/campaign_images/')),
                ('doc1', models.ImageField(blank=True, null=True, upload_to='campaign/docs/')),
                ('doc2', models.ImageField(blank=True, null=True, upload_to='campaign/docs/')),
                ('doc3', models.ImageField(blank=True, null=True, upload_to='campaign/docs/')),
                ('approval_status', models.CharField(choices=[('No_Request', 'No_Request'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=240)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RevisionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('cause_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.causeedit')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportedCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('message', models.CharField(max_length=240)),
                ('approval_status', models.CharField(choices=[('No_Request', 'No_Request'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=240)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('doc_file', models.FileField(blank=True, null=True, upload_to='campaign/documents/')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='campaigns.campaign')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaigncategory'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BankKYCEdit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('bank_data', models.JSONField(default=dict)),
                ('pan_card_image', models.ImageField(blank=True, null=True, upload_to='campaign/kyc/')),
                ('adhar_card_image', models.ImageField(blank=True, null=True, upload_to='campaign/kyc/')),
                ('passbook_image', models.ImageField(blank=True, null=True, upload_to='campaign/kyc/')),
                ('approval_status', models.CharField(choices=[('No_Request', 'No_Request'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=240)),
                ('bank_kyc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.bankkyc')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bankkyc',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_kyc', to='campaigns.campaign'),
        ),
    ]
