# Generated by Django 4.2 on 2024-03-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankkyc',
            name='bank_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
