# Generated by Django 4.2 on 2024-04-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedcampaign',
            name='contact_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reportedcampaign',
            name='email',
            field=models.EmailField(blank=True, max_length=245, null=True),
        ),
    ]
