# Generated by Django 4.2.7 on 2024-01-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='story',
            field=models.TextField(blank=True, null=True),
        ),
    ]
