# Generated by Django 4.2 on 2024-03-28 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='transfer_details',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='withdrawal_status',
        ),
    ]
