# Generated by Django 4.2.7 on 2024-01-09 09:09

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('account_holder_name', models.CharField(max_length=124)),
                ('account_number', models.PositiveIntegerField()),
                ('bank_name', models.CharField(max_length=124)),
                ('branch_name', models.CharField(max_length=124)),
                ('ifsc_code', models.CharField(max_length=124)),
                ('passbook_image', models.ImageField(blank=True, null=True, upload_to='static/media_files/campaign/kyc/')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kyc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('pan_card', models.CharField(max_length=10)),
                ('pan_card_image', models.ImageField(blank=True, null=True, upload_to='static/media_files/campaign/kyc/')),
                ('adhar_card', models.CharField(max_length=16)),
                ('adhar_card_front', models.ImageField(blank=True, null=True, upload_to='static/media_files/campaign/kyc/')),
                ('adhar_card_back', models.ImageField(blank=True, null=True, upload_to='static/media_files/campaign/kyc/')),
                ('other_details', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('tandc_accept', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media_files/campaign/campaign_images/'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 9, 9, 9, 48, 604642, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='goal_amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0, message='Value must be greater than or equal to 100'), django.core.validators.MaxValueValidator(1000000, message='Value must be less than or equal to 1000000')]),
        ),
        migrations.AlterField(
            model_name='campaigncategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media_files/campaign/catagory/'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='doc_file',
            field=models.FileField(blank=True, null=True, upload_to='static/media_files/campaign/documents/'),
        ),
        migrations.DeleteModel(
            name='CampaignKycBenificiary',
        ),
        migrations.AddField(
            model_name='kyc',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='accountdetail',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_details', to='campaigns.campaign'),
        ),
    ]
