# Generated by Django 4.2.7 on 2023-12-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaigncategory',
            old_name='status',
            new_name='is_active',
        ),
    ]
