# Generated by Django 4.2.7 on 2023-12-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benificiarybankdetails',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='campaigncatagory',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='kycdetails',
            options={'ordering': ('-created_at',)},
        ),
    ]
