# Generated by Django 4.2.7 on 2024-02-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
