# Generated by Django 4.2.7 on 2024-01-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(max_length=124),
        ),
    ]
