# Generated by Django 4.2.7 on 2023-12-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_benificiarybankdetails_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benificiarybankdetails',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterModelOptions(
            name='campaigncatagory',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterModelOptions(
            name='kycdetails',
            options={'ordering': ('-created_on',)},
        ),
        migrations.RenameField(
            model_name='benificiarybankdetails',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='benificiarybankdetails',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='campaigncatagory',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='campaigncatagory',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='kycdetails',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='kycdetails',
            old_name='updated_at',
            new_name='updated_on',
        ),
    ]
