# Generated by Django 4.2.7 on 2023-12-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_rename_status_campaigncategory_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='is_successfull',
            new_name='is_successful',
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_withdrawal',
            field=models.BooleanField(default=False),
        ),
    ]
