# Generated by Django 4.2 on 2024-04-22 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_reportedcampaign_contact_no_reportedcampaign_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankkyc',
            name='adhar_card',
        ),
        migrations.RemoveField(
            model_name='bankkyc',
            name='adhar_card_image',
        ),
        migrations.RemoveField(
            model_name='bankkyc',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='bankkyc',
            name='pan_card',
        ),
        migrations.RemoveField(
            model_name='bankkyc',
            name='pan_card_image',
        ),
        migrations.RemoveField(
            model_name='bankkyc',
            name='status',
        ),
    ]
