# Generated by Django 4.2 on 2024-03-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_bankkyc_created_on_alter_bankkyc_updated_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankkyc',
            name='bank_data',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
