# Generated by Django 4.2.7 on 2024-02-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_campaign_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankkyc",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Approved", "Approved")],
                default="Pending",
                max_length=124,
            ),
        ),
    ]
