# Generated by Django 4.2.7 on 2024-02-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_alter_accountdetail_id_alter_bankkyc_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankkyc",
            name="account_number",
            field=models.CharField(max_length=124),
        ),
    ]
