# Generated by Django 4.2.7 on 2024-01-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_rename_is_successfull_campaign_is_successful_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_image',
            field=models.ImageField(blank=True, null=True, upload_to='campaign_images/'),
        ),
    ]
