# Generated by Django 4.2 on 2024-05-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_remove_bankkyc_adhar_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
