# Generated by Django 4.2.7 on 2024-01-09 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_documents_content_alter_documents_doc_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='doc_file',
            field=models.FileField(blank=True, null=True, upload_to='static/media_files/campaign/documents/'),
        ),
    ]
