# Generated by Django 4.2.7 on 2023-12-19 06:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_benificiarybankdetails_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='course',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='is_scholarship',
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('doc_name', models.CharField(max_length=124)),
                ('doc_file', models.FileField(blank=True, null=True, upload_to='static/media_files/')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='campaigns.campaign')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
    ]
