# Generated by Django 4.2.7 on 2024-01-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_campaign_summary_alter_campaign_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='rasing_for',
            field=models.CharField(choices=[('Self', 'Self'), ('Other', 'Other'), ('Family', 'Family'), ('Charity', 'Charity')], max_length=124),
        ),
    ]
