# Generated by Django 4.2 on 2024-01-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_rename_is_successfull_campaign_is_successful_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_std_benenfited',
            field=models.BooleanField(default=False),
        ),
    ]
