# Generated by Django 4.2.7 on 2024-02-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0003_alter_bankkyc_account_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountdetail",
            name="account_number",
            field=models.CharField(max_length=124),
        ),
    ]
