# Generated by Django 4.2 on 2024-01-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_rename_is_successfull_campaign_is_successful_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause_title', models.CharField(max_length=100)),
                ('cause_img', models.ImageField(blank=True, null=True, upload_to='static/media_files/')),
            ],
        ),
    ]
