# Generated by Django 4.2 on 2024-03-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_causeedit_bankkycedit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='causeedit',
            name='document_image',
        ),
        migrations.AddField(
            model_name='causeedit',
            name='document_image1',
            field=models.ImageField(blank=True, null=True, upload_to='campaign/campaign_images/'),
        ),
        migrations.AddField(
            model_name='causeedit',
            name='document_image2',
            field=models.ImageField(blank=True, null=True, upload_to='campaign/campaign_images/'),
        ),
        migrations.AddField(
            model_name='causeedit',
            name='document_image3',
            field=models.ImageField(blank=True, null=True, upload_to='campaign/campaign_images/'),
        ),
        migrations.AlterField(
            model_name='causeedit',
            name='campaign_image',
            field=models.ImageField(blank=True, null=True, upload_to='campaign/campaign_images/'),
        ),
    ]
