# Generated by Django 4.2.7 on 2023-12-19 06:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_remove_campaign_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignKycBenificiary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('account_holder_name', models.CharField(max_length=124)),
                ('account_number', models.PositiveIntegerField()),
                ('bank_name', models.CharField(max_length=124)),
                ('branch_name', models.CharField(max_length=124)),
                ('ifsc_code', models.CharField(max_length=124)),
                ('passbook_image', models.ImageField(blank=True, null=True, upload_to='static/media_files/')),
                ('pan_card', models.CharField(max_length=10)),
                ('pan_card_image', models.ImageField(blank=True, null=True, upload_to='static/media_files/')),
                ('adhar_card', models.CharField(max_length=16)),
                ('adhar_card_image', models.ImageField(blank=True, null=True, upload_to='static/media_files/')),
                ('other_details', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='campaigns.campaign')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='kycdetails',
            name='campaign',
        ),
        migrations.DeleteModel(
            name='BenificiaryBankDetails',
        ),
        migrations.DeleteModel(
            name='KycDetails',
        ),
    ]
