# Generated by Django 4.2 on 2024-01-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_alter_campaign_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media_files/campaign_images/'),
        ),
    ]
