# Generated by Django 4.2 on 2024-03-20 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_remove_causeedit_document_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causeedit',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='causeedit',
            name='document_image1',
            field=models.ImageField(blank=True, null=True, upload_to='campaign/docs/'),
        ),
        migrations.AlterField(
            model_name='causeedit',
            name='document_image2',
            field=models.ImageField(blank=True, null=True, upload_to='campaign/docs/'),
        ),
        migrations.AlterField(
            model_name='causeedit',
            name='document_image3',
            field=models.ImageField(blank=True, null=True, upload_to='campaign/docs/'),
        ),
    ]
