# Generated by Django 4.2.7 on 2024-02-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0004_revisionhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaigncategory",
            name="slug",
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
