# Generated by Django 4.1 on 2024-06-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_alter_campaigncategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='c_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
