# Generated by Django 4.2.7 on 2024-01-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_campaign_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media_files/campaign_images/'),
        ),
        migrations.AlterField(
            model_name='campaigncategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media_files/catagory/'),
        ),
        migrations.AlterField(
            model_name='campaignkycbenificiary',
            name='adhar_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media_files/kyc/'),
        ),
        migrations.AlterField(
            model_name='campaignkycbenificiary',
            name='pan_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media_files/kyc/'),
        ),
        migrations.AlterField(
            model_name='campaignkycbenificiary',
            name='passbook_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media_files/kyc/'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='doc_file',
            field=models.FileField(blank=True, null=True, upload_to='static/media_files/documents/'),
        ),
    ]
