# Generated by Django 4.2 on 2024-01-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaigncause'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='static/media_files/campaign_images/'),
        ),
    ]
