# Generated by Django 4.2 on 2024-01-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_campaign_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='rasing_for',
            field=models.CharField(choices=[('Self', 'Self'), ('CHARITY', 'CHARITY'), ('Family/Friends', 'Family/Friends')], max_length=124),
        ),
    ]
