# Generated by Django 4.2 on 2023-12-21 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaignkycbenificiary_remove_kycdetails_campaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donors', to='campaigns.campaigncatagory'),
        ),
    ]
