# Generated by Django 5.0.8 on 2024-08-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_c_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='c_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
