# Generated by Django 4.2.7 on 2024-02-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0005_campaigncategory_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankkyc",
            name="account_number",
            field=models.CharField(max_length=240),
        ),
    ]
