# Generated by Django 4.2 on 2024-03-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_alter_causeedit_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankkycedit',
            name='adhar_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='campaign/kyc/'),
        ),
        migrations.AddField(
            model_name='bankkycedit',
            name='pan_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='campaign/kyc/'),
        ),
        migrations.AddField(
            model_name='bankkycedit',
            name='passbook_image',
            field=models.ImageField(blank=True, null=True, upload_to='campaign/kyc/'),
        ),
    ]
