# Generated by Django 4.2.7 on 2024-01-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_alter_campaign_campaign_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='days_left',
            field=models.IntegerField(default=0),
        ),
    ]
