# Generated by Django 4.2.7 on 2024-01-23 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_alter_kyc_adhar_card_back_alter_kyc_adhar_card_front_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='days_left',
        ),
    ]
