# Generated by Django 4.2 on 2024-03-20 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_bankkycedit_adhar_card_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='causeedit',
            old_name='document_image1',
            new_name='doc1',
        ),
        migrations.RenameField(
            model_name='causeedit',
            old_name='document_image2',
            new_name='doc2',
        ),
        migrations.RenameField(
            model_name='causeedit',
            old_name='document_image3',
            new_name='doc3',
        ),
    ]
