# Generated by Django 4.2.7 on 2024-02-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0006_alter_bankkyc_account_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankkyc",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("No_Request", "No_Request"),
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="No_Request",
                max_length=240,
            ),
        ),
        migrations.AddField(
            model_name="bankkyc",
            name="bank_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
