# Generated by Django 4.2 on 2024-01-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_alter_campaign_rasing_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='summary',
            field=models.TextField(max_length=100),
        ),
    ]
