# Generated by Django 4.2.7 on 2024-01-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_remove_campaign_days_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='zakat_eligible',
            field=models.BooleanField(default=False),
        ),
    ]
