# Generated by Django 4.2 on 2023-12-21 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_alter_campaign_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaigncatagory'),
        ),
    ]
