# Generated by Django 4.2.7 on 2024-02-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0007_bankkyc_approval_status_bankkyc_bank_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("No_Request", "No_Request"),
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="No_Request",
                max_length=240,
            ),
        ),
    ]
