# Generated by Django 4.2 on 2024-03-20 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_rename_document_image1_causeedit_doc1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankkycedit',
            name='bank_kyc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.bankkyc'),
        ),
    ]
