# Generated by Django 4.2.7 on 2024-01-24 07:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_alter_campaign_zakat_eligible'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankKYC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('account_holder_name', models.CharField(max_length=124)),
                ('account_number', models.PositiveIntegerField()),
                ('bank_name', models.CharField(max_length=124)),
                ('branch_name', models.CharField(max_length=124)),
                ('ifsc_code', models.CharField(max_length=124)),
                ('passbook_image', models.ImageField(blank=True, null=True, upload_to='campaign/kyc/')),
                ('pan_card', models.CharField(max_length=10)),
                ('pan_card_image', models.ImageField(upload_to='campaign/kyc/')),
                ('adhar_card', models.CharField(max_length=16)),
                ('adhar_card_front', models.ImageField(upload_to='campaign/kyc/')),
                ('adhar_card_back', models.ImageField(upload_to='campaign/kyc/')),
                ('other_details', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('tandc_accept', models.BooleanField(default=False)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_kyc', to='campaigns.campaign')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
    ]
