# Generated by Django 4.2.7 on 2024-02-27 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("campaigns", "0008_campaign_approval_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
