# Generated by Django 4.2 on 2024-03-20 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_alter_bankkycedit_bank_kyc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankkycedit',
            old_name='adhar_card_image',
            new_name='adhar_image',
        ),
        migrations.RenameField(
            model_name='bankkycedit',
            old_name='pan_card_image',
            new_name='pan_image',
        ),
    ]
