# Generated by Django 4.2.7 on 2024-01-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_bankkyc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankkyc',
            name='adhar_card_back',
            field=models.ImageField(blank=True, null=True, upload_to='campaign/kyc/'),
        ),
        migrations.AlterField(
            model_name='bankkyc',
            name='adhar_card_front',
            field=models.ImageField(blank=True, null=True, upload_to='campaign/kyc/'),
        ),
        migrations.AlterField(
            model_name='bankkyc',
            name='pan_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='campaign/kyc/'),
        ),
    ]
