# Generated by Django 4.2 on 2024-01-28 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_campaignmodification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignmodification',
            name='modified_fields',
        ),
    ]
