# Generated by Django 4.2 on 2024-01-25 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0009_campaignview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view', to=settings.AUTH_USER_MODEL),
        ),
    ]
