# Generated by Django 4.2.7 on 2024-01-29 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_alter_bankkyc_adhar_card_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='goal_amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0, message='Value must be greater than or equal to 100'), django.core.validators.MaxValueValidator(1000000000, message='Value must be less than or equal to 1000000')]),
        ),
    ]
