# Generated by Django 4.2 on 2024-02-02 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_remove_campaignmodification_modified_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampaignModification',
        ),
    ]
