# Generated by Django 4.2 on 2024-03-08 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_alter_campaign_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='campaign',
        ),
        migrations.DeleteModel(
            name='AccountDetail',
        ),
        migrations.DeleteModel(
            name='Kyc',
        ),
    ]
