# Generated by Django 4.2.7 on 2024-01-30 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_alter_campaign_goal_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='adhar_card_back',
            new_name='adhar_card_image',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='adhar_card_front',
        ),
    ]
