# Generated by Django 4.2 on 2024-02-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_delete_campaignmodification'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='commentbox',
            field=models.TextField(blank=True, null=True),
        ),
    ]
