# Generated by Django 4.2 on 2024-01-26 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_alter_campaignview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_view',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_campaign', to='campaigns.campaignview'),
        ),
        migrations.AlterField(
            model_name='campaignview',
            name='campaign',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camp_view', to='campaigns.campaign'),
        ),
    ]
