# Generated by Django 4.2 on 2024-01-26 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_campaign_campaign_view_alter_campaignview_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignview',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camp_view', to='campaigns.campaign'),
        ),
    ]
