# Generated by Django 4.2 on 2024-03-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_remove_revisionhistory_campaign_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causeedit',
            name='approval_status',
            field=models.CharField(choices=[('No_Request', 'No_Request'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=240),
        ),
    ]
