# Generated by Django 4.2 on 2024-03-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_alter_causeedit_approval_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankkycedit',
            old_name='pan_image',
            new_name='adhar_card_image',
        ),
        migrations.RenameField(
            model_name='bankkycedit',
            old_name='adhar_image',
            new_name='pan_card_image',
        ),
    ]
