# Generated by Django 4.2 on 2024-02-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_alter_campaignview_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncategory',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
