# Generated by Django 4.2 on 2024-02-04 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_campaignmodification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampaignModification',
        ),
    ]
