# Generated by Django 4.2 on 2024-03-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_reportedcampaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='campaign_data',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='is_admin_approved',
        ),
        migrations.AlterField(
            model_name='campaigncategory',
            name='slug',
            field=models.CharField(blank=True, max_length=130, null=True, unique=True),
        ),
    ]
