# Generated by Django 4.2 on 2024-03-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_remove_campaign_approval_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankkyc',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='bankkyc',
            name='bank_data',
        ),
        migrations.AlterField(
            model_name='bankkycedit',
            name='approval_status',
            field=models.CharField(choices=[('No_Request', 'No_Request'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=240),
        ),
    ]
