# Generated by Django 4.2 on 2024-03-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_remove_bankkyc_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='campaign/category/'),
        ),
    ]
