# Generated by Django 4.2 on 2024-03-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_alter_campaigncategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='transfer_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='withdrawal_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=124),
        ),
    ]
