# Generated by Django 4.2 on 2024-03-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0018_campaign_transfer_details_campaign_withdrawal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='withdrawal_status',
            field=models.CharField(choices=[('No_Request', 'No_Request'), ('Paid', 'Paid'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='No_Request', max_length=124),
        ),
    ]
