# Generated by Django 3.2 on 2023-12-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pgsetting',
            old_name='cuurency_position',
            new_name='currency_position',
        ),
        migrations.RenameField(
            model_name='pgsetting',
            old_name='currency_symobl',
            new_name='currency_symbol',
        ),
        migrations.RenameField(
            model_name='pgsetting',
            old_name='fee_for_donaion',
            new_name='fee_for_donation',
        ),
        migrations.AlterField(
            model_name='pgsetting',
            name='decimal_format',
            field=models.CharField(max_length=124),
        ),
    ]
