# Generated by Django 3.2 on 2023-12-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0002_auto_20231212_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrtransfer',
            old_name='QR_Path',
            new_name='qr_Path',
        ),
        migrations.AlterField(
            model_name='razorpay',
            name='razorpay_key',
            field=models.CharField(max_length=154),
        ),
        migrations.AlterField(
            model_name='razorpay',
            name='razorpay_secret',
            field=models.CharField(max_length=154),
        ),
    ]
