# Generated by Django 3.2 on 2023-12-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0003_auto_20231212_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrtransfer',
            old_name='qr_Path',
            new_name='qr_path',
        ),
    ]
