# Generated by Django 4.2 on 2024-03-08 08:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('fee_percent', models.IntegerField()),
                ('bank_details', models.TextField()),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PGSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('currency_code', models.CharField(max_length=50)),
                ('currency_symbol', models.CharField(max_length=10)),
                ('fee_for_donation', models.IntegerField()),
                ('currency_position', models.CharField(max_length=124)),
                ('decimal_format', models.CharField(max_length=124)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhonePay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('phonepay_key', models.CharField(max_length=154)),
                ('phonepay_secret', models.CharField(max_length=154)),
                ('fee_percent', models.IntegerField()),
                ('fee_cents', models.IntegerField()),
                ('is_enabled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
    ]
