# Generated by Django 4.2 on 2024-03-08 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateways', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayPal',
        ),
        migrations.DeleteModel(
            name='QRTransfer',
        ),
        migrations.DeleteModel(
            name='RazorPay',
        ),
        migrations.DeleteModel(
            name='Stripe',
        ),
    ]
