# Generated by Django 4.2.7 on 2023-12-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateways', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banktransfer',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='paypal',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='pgsetting',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='phonepay',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='qrtransfer',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='razorpay',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='stripe',
            options={'ordering': ('-created_at',)},
        ),
    ]
