# Generated by Django 4.2.7 on 2023-12-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateways', '0002_alter_banktransfer_options_alter_paypal_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banktransfer',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterModelOptions(
            name='paypal',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterModelOptions(
            name='pgsetting',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterModelOptions(
            name='phonepay',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterModelOptions(
            name='qrtransfer',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterModelOptions(
            name='razorpay',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterModelOptions(
            name='stripe',
            options={'ordering': ('-created_on',)},
        ),
        migrations.RenameField(
            model_name='banktransfer',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='banktransfer',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='paypal',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='paypal',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='pgsetting',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='pgsetting',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='phonepay',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='phonepay',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='qrtransfer',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='qrtransfer',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='razorpay',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='razorpay',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='stripe',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='stripe',
            old_name='updated_at',
            new_name='updated_on',
        ),
    ]
