# Generated by Django 4.2 on 2024-02-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateways', '0002_rename_status_banktransfer_is_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgsetting',
            name='currency_position',
            field=models.CharField(choices=[('₹99 - left', '₹99 - left'), ('99₹ - right', '99₹ - right')], max_length=15),
        ),
        migrations.AlterField(
            model_name='pgsetting',
            name='decimal_format',
            field=models.CharField(choices=[('10,989.95', '10,989.95'), ('10.989,95', '10.989,95')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pgsetting',
            name='fee_for_donation',
            field=models.IntegerField(choices=[('0%', '0%'), ('1%', '1%'), ('2%', '2%'), ('3%', '3%'), ('4%', '4%'), ('5%', '5%'), ('6%', '6%'), ('7%', '7%'), ('8%', '8%'), ('9%', '9%'), ('10%', '10%'), ('15%', '15%')]),
        ),
    ]
